##
## References
##
#menu "ECpdsBase"
#name "removeDataTransfer"
#group "update"

##
## Variable(s)
##
#prompt "transferId;Transfer id;%"

##
## Request(s)
##
CHUNK 1000 UPDATE UPLOAD_HISTORY SET DAT_ID = NULL
  WHERE UPH_ID IN (
    SELECT UPH_ID FROM UPLOAD_HISTORY UPH, DATA_TRANSFER DAT
    WHERE UPH.DAT_ID = DAT.DAT_ID
    AND UPH.DAT_ID = '$transferId'
);

CHUNK 1000 UPDATE INCOMING_HISTORY SET DAT_ID = NULL
  WHERE INH_ID IN (
    SELECT INH_ID FROM INCOMING_HISTORY INH, DATA_TRANSFER DAT
    WHERE INH.DAT_ID = DAT.DAT_ID
    AND INH.DAT_ID = '$transferId'
);

CHUNK 1000 DELETE FROM TRANSFER_HISTORY
  WHERE TRH_ID IN (
    SELECT TRH_ID FROM TRANSFER_HISTORY TRH, DATA_TRANSFER DAT
    WHERE TRH.DAT_ID = DAT.DAT_ID
    AND TRH.DAT_ID = '$transferId'
);

CHUNK 1000 DELETE FROM PUBLICATION
  WHERE PUB_ID IN (
    SELECT PUB_ID FROM PUBLICATION PUB, DATA_TRANSFER DAT
    WHERE PUB.DAT_ID = DAT.DAT_ID
    AND PUB.DAT_ID = '$transferId'
);

CHUNK 1 DELETE FROM DATA_TRANSFER
  WHERE DAT_ID IN (
    SELECT DAT_ID FROM DATA_TRANSFER
    WHERE DAT_ID = '$transferId'
);
