#
# File docker-compose.yml
#
# Purpose: Docker compose for deploying the OpenPDS infrastructure in the Linux environment
#
# In adition to the options configured in this file please also check the following:
#
# - etc/ecpds/database/mysqld.cnf
# - etc/ecpds/master/ecmwf.properties
# - etc/ecpds/monitor/ecmwf.properties
# - etc/ecpds/mover/ecmwf.properties
#
# (c) Copyright ECMWF 2019-2024 - Laurent Gougeon (syi@ecmwf.int)
#

services:
  # The OpenPDS Database (MariaDB) enables persistent storage for configurations, metadata and history
  database:
    container_name: database
    hostname: ecpds-database
    network_mode: host
    image: ${ECPDS_REPOSITORY:-ecpds}/database:${TAG:-latest}
    restart: unless-stopped
    # Database interface/port defined in 'etc/ecpds/database/mysqld.cnf'
    volumes:
      - "${ECPDS_ROOT_PATH:-}/var/lib/ecpds/database:/var/lib/mysql"
      - "${ECPDS_ROOT_PATH:-}/etc/ecpds/database:/etc/mysql/conf.d"

  # The ECPDS Master-Server (backend) implements the business logic of the application
  master:
    container_name: master
    hostname: ecpds-master
    network_mode: host
    environment:
      # Setting maximum heap size for the Master-Server
      ALLOCATED_MEMORY: 1G
      # Exposed IP address used to bind the public services (ecpds, ftp)
      EXTERNAL_ADDRESS: 0.0.0.0
      # Dedicated to data traffic between the internal components (jmx, rmi)
      INTERNAL_ADDRESS: 127.0.0.1
      # Ports for the Master-Server services
      PORT_JMX: 2062 # Java Management Extensions (monitoring & management)
      PORT_CALLBACK: 2600 # Java Remote Method Invocation (communication between components)
      PORT_ECPDS: 2640 # Dedicated service for ecpds command
      PORT_FTP: 2021 # Virtual FTP Server
      # Database related parameters (database interface/port must be the same as in 'etc/ecpds/database/mysqld.cnf')
      DATABASE_ALIAS: sequential://localhost:3309/ecpds
      DATABASE_MIN_SPOOL_SIZE: 5
      DATABASE_MAX_SPOOL_SIZE: 50
      # Define rollover strategy for master.log
      LOG_ROLLOVER_SIZE_MAX: 100MB # Maximum size the log file is allowed to reach before being rolled over
      LOG_ROLLOVER_SIZE_KEEP: 20 # Maximum number of backup files to keep
      # Define rollover strategy for request.log, operator.log, event.log & splunk.log
      LOG_ROLLOVER_DATE_PATTERN: dd-MM-yyyy # Date pattern for renaming current log file after rollover
      LOG_ROLLOVER_DATE_KEEP: 10d # Keep backup files which are newer than the specified duration
      # Log levels for log4j2 (off, fatal, error, warn, info, debug, trace, all)
      LOG_LEVEL: debug
      # Interactions with various ECMWF services (smtp, opsview, nagios, ecaccess, eccmd)
      METADATA_MISSING_CONTACTS_MAIL:
      SMTP_HOST:
      SMTP_FROM:
      OPSVIEW_HOST:
      ECACCESS_ADDRESS:
      ECCMD_ADDRESS:
      PORT_ECCMD: 640
      # Miscellaneous parameters
      RETRIEVAL_MAX_SPOOL_SIZE: 50 # Maximum number of parallel retrievals
      # Java Virtual Machine options
      JAVA_OPTS: -XX:+UseG1GC # The G1 Garbage Collector
    image: ${ECPDS_REPOSITORY:-ecpds}/master:${TAG:-latest}
    restart: unless-stopped
    volumes:
      - "${ECPDS_ROOT_PATH:-}/var/log/ecpds/master:/var/log/ecpds/master"
      - "${ECPDS_ROOT_PATH:-}/var/tmp/ecpds/master:/var/tmp/ecpds/master"
      - "${ECPDS_ROOT_PATH:-}/var/lib/ecpds/master:/var/lib/ecpds/master"
      - "${ECPDS_ROOT_PATH:-}/etc/ecpds:/etc/ecpds"
    depends_on:
      - database

  # The Monitoring interface (frontend) allow monitoring, controlling and administrating the application
  monitor:
    container_name: monitor
    hostname: ecpds-monitor
    network_mode: host
    environment:
      # Setting maximum heap size for the Monitor-Server
      ALLOCATED_MEMORY: 1G
      # Exposed IP address used to bind the public services (http/s)
      EXTERNAL_ADDRESS: 0.0.0.0
      # Dedicated to data traffic between the internal components (jmx, rmi)
      INTERNAL_ADDRESS: 127.0.0.1
      # Ports for the Monitor-Server services
      PORT_JMX: 3062 # Java Management Extensions (monitoring & management)
      PORT_CALLBACK: 3600 # Java Remote Method Invocation (communication between components)
      PORT_HTTPS: 3443 # Web monitoring interface (https)
      # Connectivity to the Master-Server
      MASTER_ADDRESS: localhost
      PORT_MASTER: 2600
      # Define rollover strategy for monitor.log
      LOG_ROLLOVER_SIZE_MAX: 100MB # Maximum size the log file is allowed to reach before being rolled over
      LOG_ROLLOVER_SIZE_KEEP: 20 # Maximum number of backup files to keep
      # Log levels for log4j2 (off, fatal, error, warn, info, debug, trace, all)
      LOG_LEVEL: debug
      # Password to unlock the 'etc/ecpds/monitor/ecpds-monitor.pfx' keystore
      KEYSTORE_PASSWORD: s5w8g771
      # Personalisation of monitoring web interface
      MONITOR_NICKNAME: "PDS"
      MONITOR_TITLE: "Personal Data Store"
      MONITOR_COLOR: "#0079d3"
      # Interactions with various ECMWF services (requirements, nagios)
      REQUIREMENTS_URL:
      # Miscellaneous parameters
      USE_CACHE: "no"
      MASTER_URL_LIST:
      DEFAULT_SOURCE_HOST_ID:
      # Java Virtual Machine options
      JAVA_OPTS: -XX:+UseG1GC # The G1 Garbage Collector
    image: ${ECPDS_REPOSITORY:-ecpds}/monitor:${TAG:-latest}
    restart: unless-stopped
    volumes:
      - "${ECPDS_ROOT_PATH:-}/var/log/ecpds/monitor:/var/log/ecpds/monitor"
      - "${ECPDS_ROOT_PATH:-}/var/tmp/ecpds/monitor:/var/tmp/ecpds/monitor"
      - "${ECPDS_ROOT_PATH:-}/etc/ecpds:/etc/ecpds"
    depends_on:
      - master

  # The Data-Mover (frontend) make it possible to store objects and to perform incoming and outgoing
  # data transfers
  mover:
    container_name: mover
    hostname: ecpds-mover
    network_mode: host
    environment:
      # Setting maximum heap size for the Mover-Server
      ALLOCATED_MEMORY: 1G
      # Exposed IP address used to bind the public services (http/s, ftp, sftp, ecproxy)
      EXTERNAL_ADDRESS: 0.0.0.0
      # Dedicated to data traffic between the internal components (jmx, rmi)
      INTERNAL_ADDRESS: 127.0.0.1
      # Ports for the Monitor-Server services
      PORT_JMX: 4062 # Java Management Extensions (monitoring & management)
      PORT_CALLBACK: 4600 # Java Remote Method Invocation (communication between components)
      PORT_HTTP: 4080 # Web data-portal interface (http)
      PORT_HTTPS: 4443 # Web data-portal interface (https)
      PORT_MQTT: 4183 # MQTT interface (mqtt)
      PORT_MQTTS: 4883 # MQTT interface (mqtts)
      PORT_FTP: 4021 # Data-portal interface (ftp)
      PORT_SSH: 4022 # Data-portal interface (sftp/scp)
      PORT_ECPROXY: 4640 # Dedicated service for ecpds command
      # Connectivity to the Master-Server
      MASTER_ADDRESS: localhost
      PORT_MASTER: 2600
      # Define rollover strategy for mover.log
      LOG_ROLLOVER_SIZE_MAX: 100MB # Maximum size the log file is allowed to reach before being rolled over
      LOG_ROLLOVER_SIZE_KEEP: 20 # Maximum number of backup files to keep
      # Log levels for log4j2 (off, fatal, error, warn, info, debug, trace, all)
      LOG_LEVEL: debug
      # Password to unlock the 'etc/ecpds/mover/ecpds-mover.pfx' keystore
      KEYSTORE_PASSWORD: s5w8g771
      # Personalisation of monitoring web interface
      MOVER_TITLE: "Personal Data Store (PDS)"
      MOVER_COLOR: "#0079d3"
      # Miscellaneous parameters
      OPERATION: "yes" # Set to 'no' to produce random data for missing files (for testing purpose only)
      # Java Virtual Machine options
      JAVA_OPTS: -XX:+UseG1GC # The G1 Garbage Collector
    image: ${ECPDS_REPOSITORY:-ecpds}/mover:${TAG:-latest}
    restart: unless-stopped
    volumes:
      - "${ECPDS_ROOT_PATH:-}/var/log/ecpds/mover:/var/log/ecpds/mover"
      - "${ECPDS_ROOT_PATH:-}/var/tmp/ecpds/mover:/var/tmp/ecpds/mover"
      - "${ECPDS_ROOT_PATH:-}/var/lib/ecpds/mover:/var/lib/ecpds/mover"
      - "${ECPDS_ROOT_PATH:-}/etc/ecpds:/etc/ecpds"
    depends_on:
      - master
