##
## References
##
#menu "ECpdsBase"
#name "getDataFilesByGroupBy"
#group "select"

##
## Request(s)
##
SELECT DAF_GROUP_BY,DATA_FILE.DAF_ID
FROM
  DATA_FILE,DATA_TRANSFER
WHERE
  DAF_DELETED = 0
  AND DAF_DOWNLOADED = 0
  AND (NOT DAF_GROUP_BY is NULL)
  AND (NOT DAF_GROUP_BY like 'ACQ_%')
  AND DATA_FILE.DAF_ID = DATA_TRANSFER.DAF_ID
  AND DAT_DELETED = 0
  AND STA_CODE in ('SCHE','FETC')
GROUP BY
  DAF_GROUP_BY,DATA_FILE.DAF_ID
ORDER BY
  DAF_GROUP_BY
