##
## References
##
#menu "ECpdsBase"
#name "getDataTransferNotDoneOnDate"
#group "select"

##
## Variable(s)
##
#prompt "currentDate;Current date;%;java.sql.Timestamp"

##
## Request(s)
##
SELECT DAF.DAF_ID, DAF_SIZE, DAF_TIME_STEP, DAF_ARRIVED_TIME, DAT.DAT_ID, DAT.DES_NAME, HOS_NAME, TRS_NAME, DAT_TARGET, DAT.STA_CODE,
  DAT_USER_STATUS, DAT_SENT, DAT_DURATION, DAT_PRIORITY, DAT_SCHEDULED_TIME, DAT_FIRST_FINISH_TIME, DAT_FINISH_TIME, DAF_META_STREAM, DAF_META_TARGET,
  DAF_META_TIME, DAF_META_TYPE, DAF_TIME_BASE, DAF.MOV_ID AS DAF_MOV_ID, DAT.MOV_ID AS DAT_MOV_ID, DAT_RETRY_TIME, DAT_QUEUE_TIME, DAT_IDENTITY
FROM
  DATA_TRANSFER DAT USE INDEX(replicateRequest2), DATA_FILE DAF, DESTINATION DES
WHERE
  DAT.DAF_ID = DAF.DAF_ID
  AND DAT.DES_NAME = DES.DES_NAME
  AND DES_MONITOR<>0
  AND NOT DAF.MOV_ID is NULL
  AND NOT DAT.MOV_ID is NULL
  AND NOT DAT_DELETED<>0
  AND NOT DAT.STA_CODE IN ('DONE','HOLD')
  AND NOT DAF_META_STREAM = 'None'
  AND NOT DAF_META_TARGET = 'None'
  AND NOT DAF_META_TIME = 'None'
  AND DAF_TIME_STEP != '-1'
  AND DAT_SCHEDULED_TIME < '$currentDate'
