#!/bin/sh

#
# File ecenv
#
# Purpose: Data-Mover common environment variables (OpenPDS)
#
# (c) Copyright ECMWF 2011-2024 - Laurent Gougeon (syi@ecmwf.int)
#

######################
## OpenPDS directories
######################
ECPDS_APP="/usr/local/ecpds"
ECPDS_LOG="/var/log/ecpds"
ECPDS_TMP="/var/tmp/ecpds"
ECPDS_LIB="/var/lib/ecpds"

##########################################
## Set of commands used within the scripts
##########################################
bzip2=bzip2
cat=cat
cd=cd
echo=echo
find=find
grep=grep
gzip=gzip
hostname=hostname
java=java
kill=kill
lbzip2=lbzip2
ln=ln
ls=ls
mv=mv
nmap=nmap
nohup=nohup
mtr=mtr
pidof=pidof
ps=ps
ping=ping
rm=rm
sleep=sleep
sort=sort
ulimit=ulimit
wc=wc

#####################################
## Set values for OpenPDS directories
#####################################
dir_etc="/etc/ecpds/mover"
dir_mover="$ECPDS_APP/mover"
dir_htdocs="$ECPDS_APP/mover/htdocs"
dir_conf="$ECPDS_APP/mover/conf"
dir_lib="$ECPDS_APP/mover/lib"
dir_sh="$ECPDS_APP/mover/sh"
dir_log="$ECPDS_LOG/mover"
dir_tmp="$ECPDS_TMP/mover"
dir_mqtt="$ECPDS_LIB/mover/mqtt"
dir_data="$ECPDS_LIB/mover/data"

##################################
## Check the ECPDS_APP directories
##################################
if [ ! -d "$dir_htdocs" -o ! -d "$dir_conf" -o ! -d "$dir_lib" -o ! -d "$dir_sh" ]; then
  $echo "Missing directories in $ECPDS_APP!"
  exit 1
fi

################################################
## Check the log, tmp, mqtt and data directories
################################################
if [ ! -d "$dir_log" -o ! -d "$dir_tmp" -o ! -d "$dir_mqtt" -o ! -d "$dir_data" ]; then
  $echo "Missing log, tmp, mqtt or data directories!"
  exit 1
fi
