#!/bin/sh

#
# File ecenv
#
# Purpose: Master-Server common environment variables (OpenECPDS)
#
# (c) Copyright ECMWF 2011-2024 - Laurent Gougeon (syi@ecmwf.int)
#

######################
## OpenECPDS directories
######################
ECPDS_APP="/usr/local/ecpds"
ECPDS_LOG="/var/log/ecpds"
ECPDS_TMP="/var/tmp/ecpds"
ECPDS_DATA="/var/lib/ecpds"

##########################################
## Set of commands used within the scripts
##########################################
cat=cat
echo=echo
find=find
grep=grep
java=java
kill=kill
ls=ls
nohup=nohup
pidof=pidof
ps=ps
rm=rm
sleep=sleep
ulimit=ulimit
wc=wc

#####################################
## Set values for OpenECPDS directories
#####################################
dir_etc="/etc/ecpds/master"
dir_conf="$ECPDS_APP/master/conf"
dir_lib="$ECPDS_APP/master/lib"
dir_sh="$ECPDS_APP/master/sh"
dir_log="$ECPDS_LOG/master"
dir_tmp="$ECPDS_TMP/master"
dir_data="$ECPDS_DATA/master"

##################################
## Check the ECPDS_APP directories
##################################
if [ ! -d "$dir_conf" -o ! -d "$dir_lib" -o ! -d "$dir_sh" ]; then
  $echo "Missing directories in $ECPDS_APP!"
  exit 1
fi

##########################################
## Check the log, tmp and data directories
##########################################
if [ ! -d "$dir_log" -o ! -d "$dir_tmp" -o ! -d "$dir_data" ]; then
  $echo "Missing log, tmp or data directories!"
  exit 1
fi
