##
## References
##
#menu "ECpdsBase"
#name "getAllPortalTraffic"
#group "select"

##
## Request(s)
##
SELECT TIME, CONNECTIONS, BYTES_IN, BYTES_OUT, DURATION_IN, DURATION_OUT FROM (
  SELECT
    PTD_DATE              AS TIME,
    SUM(PTD_CONNECTIONS)  AS CONNECTIONS,
    SUM(PTD_BYTES_IN)     AS BYTES_IN,
    SUM(PTD_BYTES_OUT)    AS BYTES_OUT,
    SUM(PTD_DURATION_IN)  AS DURATION_IN,
    SUM(PTD_DURATION_OUT) AS DURATION_OUT
  FROM PORTAL_TRAFFIC_DAILY
  GROUP BY PTD_DATE
  UNION ALL
  SELECT
    DATE(PTR_TIME)        AS TIME,
    SUM(PTR_CONNECTIONS)  AS CONNECTIONS,
    SUM(PTR_BYTES_IN)     AS BYTES_IN,
    SUM(PTR_BYTES_OUT)    AS BYTES_OUT,
    SUM(PTR_DURATION_IN)  AS DURATION_IN,
    SUM(PTR_DURATION_OUT) AS DURATION_OUT
  FROM PORTAL_TRAFFIC
  WHERE DATE(PTR_TIME) NOT IN (SELECT DISTINCT PTD_DATE FROM PORTAL_TRAFFIC_DAILY)
    AND PTR_USER != ''
  GROUP BY DATE(PTR_TIME)
) combined
ORDER BY TIME DESC
