##
## References
##
#menu "ECpdsBase"
#name "getDataFilesToFilter"
#group "select"

##
## Variable(s)
##
#prompt "currentTimeMillis;Current Time in Milliseconds;;long"
#prompt "limit;Limit;%;int"

##
## Request(s)
##
SELECT DATA_FILE.DAF_ID,DATA_FILE.TRG_NAME,DES_FILTER_NAME,DAF_ARRIVED_TIME,DAF_TIME_STEP,DAF_ORIGINAL,
  DAF_FILTER_TIME,DAF_CHECKSUM,DAF_FILE_SYSTEM,DAF_FILE_INSTANCE,DAF_SIZE,TRG_MIN_FILTERING_COUNT,
  TRG_MIN_REPLICATION_COUNT
FROM
  DESTINATION,DATA_TRANSFER USE INDEX(replicateRequest2),DATA_FILE,TRANSFER_GROUP
WHERE
  DES_FILTER_NAME IS NOT NULL
  AND NOT DES_FILTER_NAME = 'none'
  AND NOT DES_FILTER_NAME = ''
  AND TRANSFER_GROUP.TRG_NAME = DATA_FILE.TRG_NAME
  AND TRANSFER_GROUP.TRG_FILTER<>0
  AND DATA_TRANSFER.DES_NAME = DESTINATION.DES_NAME
  AND DATA_TRANSFER.DAF_ID = DATA_FILE.DAF_ID
  AND (DATA_TRANSFER.STA_CODE = 'WAIT' OR DATA_TRANSFER.STA_CODE = 'RETR')
  AND ((DAF_FILTER_NAME IS NULL AND (DAF_FILTER_TIME IS NULL OR
    (($currentTimeMillis - DAF_FILTER_TIME) > 1800000))) OR (NOT DAF_FILTER_NAME = DES_FILTER_NAME))
  AND DAF_DELETED = 0
  AND DAT_DELETED = 0
ORDER BY
  DAT_PRIORITY ASC, DAT_QUEUE_TIME ASC, DAT_ID ASC
LIMIT $limit
