##
## References
##
#menu "ECpdsBase"
#name "getDataTransfersOnDate"
#group "select"

##
## Variable(s)
##
#prompt "fromDate;From date;%;java.sql.Timestamp"
#prompt "toDate;To date;%;java.sql.Timestamp"

##
## Request(s)
##
SELECT DAT_IDENTITY, DAF.DAF_ID, DAF_SIZE, DAF_TIME_STEP, DAF_ARRIVED_TIME, DAT.DAT_ID, DAT.DES_NAME, DAT.HOS_NAME, TRS_NAME, DAT_TARGET, DAT.STA_CODE,
  DAT_USER_STATUS, DAT_SENT, DAT_DURATION, DAT_PRIORITY, DAT_SCHEDULED_TIME, DAT_FIRST_FINISH_TIME, DAT_FINISH_TIME, DAF_META_STREAM, DAF_META_TARGET,
  DAF_META_TIME, DAF_META_TYPE, DAF_TIME_BASE, DAF.MOV_ID AS DAF_MOV_ID, DAT.MOV_ID AS DAT_MOV_ID, DAT_RETRY_TIME, DAT_QUEUE_TIME
FROM
  DATA_TRANSFER DAT, DATA_FILE DAF, DESTINATION DES
WHERE
  DAT.STA_CODE != 'HOLD'
  AND DAT_TIME_BASE != '-1'
  AND DAT_TIME_BASE >= '$fromDate'
  AND DAT_TIME_BASE < '$toDate'
  AND NOT DAT_DELETED<>0
  AND DAT.DES_NAME = DES.DES_NAME
  AND DES_MONITOR<>0
  AND NOT DAF.MOV_ID is NULL
  AND NOT DAT.MOV_ID is NULL
  AND (DES_TYPE = 5 OR DES_TYPE = 6)
  AND DAT.DAF_ID = DAF.DAF_ID
  AND NOT DAF_META_STREAM = 'None'
  AND NOT DAF_META_TARGET = 'None'
  AND NOT DAF_META_TIME = 'None'
ORDER BY DAT_IDENTITY, DAT_TIME_BASE DESC
