##
## References
##
#menu "ECpdsBase"
#name "getDestinationExts"
#group "select"

##
## Request(s)
##
SELECT DISTINCT(DES.DES_NAME), DES_RESET_FREQUENCY, DES_STOP_IF_DIRTY, DES_UPDATE, 
  COUNT(DAT_ID) AS PENDING_COUNT, SCV.SCV_ID, MIN(DAT_QUEUE_TIME) AS MIN_QUEUE_TIME,
  SCV.HOS_NAME, SCV_START_COUNT, SCV_RESET_TIME, DES.STA_CODE
FROM
  DATA_TRANSFER DAT USE INDEX(schedulerRequest), DESTINATION DES, SCHEDULER_VALUE SCV
WHERE
  DAT.STA_CODE IN ('WAIT','RETR')
  AND DAT_DELETED = 0
  AND DAT.DES_NAME = DES.DES_NAME
  AND DES.DES_ACTIVE != 0
  AND DES.SCV_ID = SCV.SCV_ID
GROUP BY DES.DES_NAME,DES.DES_RESET_FREQUENCY,DES.DES_STOP_IF_DIRTY,DES.DES_UPDATE,SCV.SCV_ID,SCV.HOS_NAME,SCV_START_COUNT,SCV_RESET_TIME,DES.STA_CODE
