##
## References
##
#menu "ECpdsBase"
#name "getDataFilesByGroupBy"
#group "select"

##
## Request(s)
##
SELECT DAF_GROUP_BY,DAF_ID
FROM DATA_FILE
WHERE
  DAF_DELETED = 0
  AND DAF_DOWNLOADED = 0
  AND DAF_GROUP_BY IS NOT NULL
  AND DAF_GROUP_BY NOT LIKE 'ACQ_%'
  AND EXISTS (
    SELECT 1 FROM DATA_TRANSFER
    WHERE DATA_TRANSFER.DAF_ID = DATA_FILE.DAF_ID
      AND DAT_DELETED = 0
      AND STA_CODE IN ('SCHE','FETC')
  )
ORDER BY
  DAF_GROUP_BY
