##
## References
##
#menu "ECpdsBase"
#name "getExistingStorageDirectories"
#group "select"

##
## Request(s)
##
SELECT
	DISTINCT(DATE(FROM_UNIXTIME(DAF_ARRIVED_TIME/1000))) AS DAF_ARRIVED_DATE,
	TRG_NAME,
	DAF_FILE_SYSTEM,
	COUNT(*) AS FILES_COUNT,
	SUM(DAF_SIZE) AS FILES_SIZE
FROM
	DATA_TRANSFER,
	DATA_FILE
WHERE
	NOT TRG_NAME IS NULL
	AND NOT DAT_DELETED
	AND DATA_TRANSFER.DAF_ID = DATA_FILE.DAF_ID
GROUP BY
	TRG_NAME,DAF_ARRIVED_DATE,DAF_FILE_SYSTEM
ORDER BY
	TRG_NAME,DAF_ARRIVED_DATE,DAF_FILE_SYSTEM
