##
## References
##
#menu "ECpdsBase"
#name "getPortalTrafficByUser"
#group "select"

##
## Variable(s)
##
#prompt "userId;Incoming user id;%"

##
## Request(s)
##
SELECT TIME, CONNECTIONS, BYTES_IN, BYTES_OUT, DURATION_IN, DURATION_OUT FROM (
  SELECT
    PTD_DATE         AS TIME,
    PTD_CONNECTIONS  AS CONNECTIONS,
    PTD_BYTES_IN     AS BYTES_IN,
    PTD_BYTES_OUT    AS BYTES_OUT,
    PTD_DURATION_IN  AS DURATION_IN,
    PTD_DURATION_OUT AS DURATION_OUT
  FROM PORTAL_TRAFFIC_DAILY
  WHERE PTD_USER = '$userId'
  UNION ALL
  SELECT
    DATE(PTR_TIME)           AS TIME,
    SUM(PTR_CONNECTIONS)     AS CONNECTIONS,
    SUM(PTR_BYTES_IN)        AS BYTES_IN,
    SUM(PTR_BYTES_OUT)       AS BYTES_OUT,
    SUM(PTR_DURATION_IN)     AS DURATION_IN,
    SUM(PTR_DURATION_OUT)    AS DURATION_OUT
  FROM PORTAL_TRAFFIC
  WHERE PTR_USER = '$userId'
    AND DATE(PTR_TIME) NOT IN (
      SELECT PTD_DATE FROM PORTAL_TRAFFIC_DAILY WHERE PTD_USER = '$userId'
    )
  GROUP BY DATE(PTR_TIME)
) combined
ORDER BY TIME DESC
