##
## References
##
#menu "ECpdsBase"
#name "getRetryingDataTransfersByGroupBy"
#group "select"

##
## Variable(s)
##
#prompt "groupBy;Group by;%"

##
## Request(s)
##
SELECT STRAIGHT_JOIN
       DAT.DAT_ID, DAT.DES_NAME, DAT.DAT_COMMENT, DAT.STA_CODE, DAT.DAT_REPLICATE_COUNT,
       DAF.DAF_ID, DAF.DAF_ORIGINAL, DAF.DAF_SIZE, DAF.DAF_ECAUTH_HOST, DAF.DAF_ECAUTH_USER
  FROM DATA_FILE DAF USE INDEX (DATA_FILE_ibfk_7)
  JOIN DATA_TRANSFER DAT USE INDEX (disseminationGroupBy)
    ON DAT.DAF_ID = DAF.DAF_ID
   AND DAT.DAT_DELETED = 0
   AND DAT.STA_CODE = 'SCHE'
   AND DAT.DAT_REPLICATE_COUNT > 0
 WHERE DAF.DAF_DELETED = 0
   AND DAF.DAF_DOWNLOADED = 0
   AND DAF.DAF_GROUP_BY = '$groupBy'
 LIMIT 10
