##
## References
##
#menu "ECpdsBase"
#name "getTransferStatisticsByDataTransferId"
#group "query"

##
## Variable(s)
##
#prompt "datId;Data Transfer ID;%"

##
## Request(s)
##
SELECT TST_ID, DAT_ID, TST_START_TIME, TST_END_TIME, TST_LOCAL_ADDRESS, TST_REMOTE_ADDRESS,
       TST_RTT_MS, TST_BYTES_SENT, TST_BYTES_RECEIVED, TST_PACING_RATE_BPS, TST_DELIVERY_RATE_BPS,
       TST_CWND, TST_SEGS_OUT, TST_SEGS_IN, TST_RAW, TST_REQUEUE_HISTORY
  FROM TRANSFER_STATISTICS
 WHERE DAT_ID = '$datId'
 ORDER BY TST_REQUEUE_HISTORY ASC, TST_START_TIME ASC
