##
## References
##
#menu "ECpdsBase"
#name "removeHost"
#group "update"

##
## Variable(s)
##
#prompt "hostName;Host name;%"

##
## Request(s)
##
DELETE FROM ASSOCIATION
  WHERE HOS_NAME = '$hostName';

DELETE FROM HOS_ECU
  WHERE HOS_NAME = '$hostName';

DELETE FROM CHANGE_LOG
  WHERE CHL_KEY_NAME = 'HOS_NAME'
  AND CHL_KEY_VALUE = '$hostName';

CHUNK 1000 UPDATE SCHEDULER_VALUE SET HOS_NAME = NULL
  WHERE HOS_NAME IN (
    SELECT HOS_NAME FROM SCHEDULER_VALUE
    WHERE HOS_NAME = '$hostName'
);

CHUNK 1000 UPDATE DATA_TRANSFER SET HOS_NAME = NULL
  WHERE DAT_ID IN (
    SELECT DAT_ID FROM DATA_TRANSFER
    WHERE HOS_NAME = '$hostName'
);

CHUNK 1000 UPDATE DATA_TRANSFER SET HOS_NAME_BACKUP = NULL, DAT_BACKUP_TIME = NULL
  WHERE DAT_ID IN (
    SELECT DAT_ID FROM DATA_TRANSFER
    WHERE HOS_NAME_BACKUP = '$hostName'
);

CHUNK 1000 UPDATE DATA_TRANSFER SET HOS_NAME_PROXY = NULL, DAT_PROXY_TIME = NULL
  WHERE DAT_ID IN (
    SELECT DAT_ID FROM DATA_TRANSFER
    WHERE HOS_NAME_PROXY = '$hostName'
);

CHUNK 1000 UPDATE DATA_FILE SET HOS_NAME_FOR_ACQUISITION = NULL
  WHERE DAF_ID IN (
    SELECT DAF_ID FROM DATA_FILE
    WHERE HOS_NAME_FOR_ACQUISITION = '$hostName'
);

CHUNK 1000 DELETE FROM TRANSFER_HISTORY
  WHERE TRH_ID IN (
    SELECT TRH_ID FROM TRANSFER_HISTORY
    WHERE HOS_NAME = '$hostName'
);

UPDATE DESTINATION
  SET HOS_NAME_FOR_SOURCE = NULL
  WHERE HOS_NAME_FOR_SOURCE = '$hostName';

UPDATE TRANSFER_GROUP
  SET HOS_NAME_FOR_BACKUP = NULL
  WHERE HOS_NAME_FOR_BACKUP = '$hostName';

UPDATE TRANSFER_SERVER
  SET HOS_NAME_FOR_REPLICATION = NULL
  WHERE HOS_NAME_FOR_REPLICATION = '$hostName';

CHUNK 1 DELETE FROM HOST
  WHERE HOS_NAME IN (
 	SELECT HOS_NAME FROM HOST
 	WHERE HOS_NAME = '$hostName'
);
