[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
loglevel=info
pidfile=/var/run/supervisord.pid
user=root

[unix_http_server]
file=/var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:master]
command=/usr/local/ecpds/standalone/start-master.sh
autostart=true
autorestart=true
startretries=3
stdout_logfile=/data/log/master/supervisord.log
stderr_logfile=/data/log/master/supervisord.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3

[program:mover]
command=/usr/local/ecpds/standalone/start-mover.sh
autostart=true
autorestart=true
startretries=3
stdout_logfile=/data/log/mover/supervisord.log
stderr_logfile=/data/log/mover/supervisord.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3

[program:monitor]
command=/usr/local/ecpds/standalone/start-monitor.sh
autostart=true
autorestart=true
startretries=3
stdout_logfile=/data/log/monitor/supervisord.log
stderr_logfile=/data/log/monitor/supervisord.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
