#!/bin/sh

#
# File lbzip2
#
# Purpose: Helper for lbzip2 (OpenPDS)
#
# (c) Copyright ECMWF 2016-2022 - Laurent Gougeon (syi@ecmwf.int)
#

##########################
## Load configuration file
##########################
if [ -f "/usr/local/ecpds/mover/sh/ecenv" ]; then
  source /usr/local/ecpds/mover/sh/ecenv
else
  # Started from Eclipse? 
  lbzip2=lbzip2
  for cmd in $lbzip2; do
    if ! command -v $cmd &> /dev/null
    then
      exit -1
    fi
  done
fi

###########################
## Start the lbzip2 command
###########################
$lbzip2 -f -k -c $1 > $2
